// Turn the data files into a TypeScript module.
//
// ⚠️ WHY THIS EXISTS. A host on React Native cannot read files — there is no `fs` on a phone — so a
// pack that ships as `.txt` + `.tsv` forces every host to bundle the data itself and hand it to
// `createPack`. That is the whole preamble this package deletes.
//
// The generated module is checked in on purpose: it is a build artefact of data that changes only
// when the pack is rebuilt, and checking it in means `npm install` is the only step a consumer runs.
// Regenerate with `npm run generate`, and the test asserts it is in sync with the source files.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const read = (f) => readFileSync(join(root, f), 'utf8');

// Backticks and `${` are the only sequences that can break a template literal. Nothing else needs
// escaping, which is why a template literal beats JSON.stringify here: no quote-doubling on 340KB.
const lit = (s) => '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';

const config = read('pack.config.json');
const frequency = read('frequency.txt').trim();
const lemmas = read('lemmas.tsv').trim();
// ⚠️ Bundled so the app has REAL RUNNING TEXT with no network. A host that had to fetch a sentence
// to show a calibration screen would make the first thing a learner sees depend on a connection.
const sample = read('sample.txt').trim();

writeFileSync(
  join(root, 'src', 'data.generated.ts'),
  `// GENERATED by build/generate.mjs — do not edit. Run \`npm run generate\` after changing the
// source files in this directory. \`data.generated.test.ts\` fails if this drifts from them.

export const CONFIG = ${config.trim()} as const;

export const FREQUENCY = ${lit(frequency)};

export const LEMMA_ROWS = ${lit(lemmas)};

export const SAMPLE = ${lit(sample)};
`,
);
console.log(`generated: ${frequency.length} bytes frequency, ${lemmas.length} bytes lemmas, ${sample.length} bytes sample`);
